on: [push]

jobs:
  mc-action:
    runs-on: ubuntu-latest
    name: run mc
    steps:
    - uses: actions/checkout@v2
    - id: mc
      uses: xdevma/mc-action@v10
      with:
        version: '2.0.0'
        gpg_key: ${{ secrets.PGP_KEY }}
        sona: ${{ secrets.SONA }}
        profile: ${{ secrets.REPO_PROFILE }}
    - run: echo repo ${{ steps.mc.outputs.repo-id }}
      shell: bash
