on: [push]

jobs:
  mc-action:
    environment: Release
    runs-on: ubuntu-latest
    name: run mc action
    steps:
    - uses: actions/checkout@v2
    - id: mc
      uses: xdevma/mc-action@v18
      with:
        version: ${{ secrets.VERSION }}
        gpg_key: ${{ secrets.PGP_KEY }}
        sona: ${{ secrets.SONA }}
        profile: ${{ secrets.REPO_PROFILE }}
    - run: echo repository ${{ steps.mc.outputs.repo-id }}
      shell: bash
