on: [push]

jobs:
  mc-action:
    runs-on: ubuntu-latest
    name: run mc
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: xdevma/mc-action@v5
      with:
        version: '2.0.0'
    - run: echo repo ${{ steps.foo.outputs.repo-id }}
      shell: bash
