on: [push]

jobs:
  mc-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: xdevma/mc-action@v2
      with:
        version: '1.2'
    - run: echo repo ${{ steps.foo.outputs.repo-id }}
      shell: bash