on:
  release:
    types: [published]

jobs:
  mc-stage-action:
    environment: Stage
    runs-on: ubuntu-latest
    name: run mc stage action
    steps:
    - uses: actions/checkout@v2
    - id: mcs
      uses: xdevma/mc-action@v120
      with:
        version: ${{ secrets.VERSION }}
        gpg_key: ${{ secrets.PGP_KEY }}
        sona: ${{ secrets.SONA }}
        profile: ${{ secrets.REPO_PROFILE }}
        gtoken: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo ${{ steps.mcs.outputs.repo-id }} > repo.id
      shell: bash
    - name: Upload repo id
      uses: actions/upload-artifact@v2
      with:
        name: repoid
        path: repo.id
  mc-release-action:
    needs: mc-stage-action
    environment: Release
    runs-on: ubuntu-latest
    name: run mc release action
    steps:
    - uses: actions/checkout@v2
    - name: Download repo id
      uses: actions/download-artifact@v2
      with:
        name: repoid
    - name: Print the final result
      shell: bash
      run: |
        echo "REPOID=$(cat repo.id)" >> $GITHUB_ENV
    - id: mcr
      uses: xdevma/mc-action@v2r
      with:
        sona: ${{ secrets.SONA }}
        profile: ${{ secrets.REPO_PROFILE }}
        repo-id: ${{ env.REPOID }}
