on:
  release:
    types: [published]

jobs:
  mcs-action:
    environment: Stage
    runs-on: ubuntu-latest
    name: run mc stage action
    steps:
    - uses: actions/checkout@v2
    - id: mc
      uses: xdevma/mc-action@v19
      with:
        version: ${{ secrets.VERSION }}
        gpg_key: ${{ secrets.PGP_KEY }}
        sona: ${{ secrets.SONA }}
        profile: ${{ secrets.REPO_PROFILE }}
    - run: echo repository ${{ steps.mc.outputs.repo-id }}
      shell: bash
  mcr-action:
    needs: mcs-action
    environment: Release
    runs-on: ubuntu-latest
    name: run mc release action
    steps:
    - uses: actions/checkout@v2
    - id: mc
      uses: xdevma/mc-action@v2r
      with:
        sona: ${{ secrets.SONA }}
        profile: ${{ secrets.REPO_PROFILE }}
