on: [push]

jobs:
  mc-action:
    runs-on: ubuntu-latest
    name: run mc
    steps:
    - uses: actions/checkout@v2
    - id: mc
      uses: xdevma/mc-action@v9
      with:
        version: '2.0.0'
        gpg_key: ${{ secrets.PGP_KEY }}
    - run: echo repo ${{ steps.mc.outputs.repo-id }}
      shell: bash
