on:
  release:
    types: [published]

jobs:
  mc-stage-action:
    environment: Stage
    runs-on: ubuntu-latest
    name: run mc stage action
    steps:
    - uses: actions/checkout@v2
    - id: mc
      uses: xdevma/mc-action@v120
      with:
        version: ${{ secrets.VERSION }}
        gpg_key: ${{ secrets.PGP_KEY }}
        sona: ${{ secrets.SONA }}
        profile: ${{ secrets.REPO_PROFILE }}
        gtoken: ${{ secrets.GITHUB_TOKEN }}
    - run: echo repository ${{ steps.mc.outputs.repo-id }}
      shell: bash
  mc-release-action:
    needs: mc-stage-action
    environment: Release
    runs-on: ubuntu-latest
    name: run mc release action
    steps:
    - uses: actions/checkout@v2
    - id: mc
      uses: xdevma/mc-action@v2r
      with:
        sona: ${{ secrets.SONA }}
        profile: ${{ secrets.REPO_PROFILE }}
        repo-id: ${{ steps.mc.outputs.repo-id }}

        